### ISSUE TITLE
LayerMenu throws errors in demo-app

### ISSUE THREAD

**Issue by sholl** [conterra/mapapps-sketching-enhanced#3]
Hi,
congrats, very nice bundle!

The demo-app throws an error when clicking on the layer menu.
`layer.js?requires={%40dojo%2Fframework%2Fmain}5.0.4%2C{system%2Capprt%2F%24_%2Capprt-binding%2F%24_%2Capprt-core%2F%24_%2Capprt-esri-init%2F%24_%2Capprt-request%2Fmain%2Capprt-vue%2Capprt-vuetify%2Cbanner%2Cconsole%2Ccoordinatetransformer%2Cct%2Fmain%2Cdataform%2Cdataview%2F%24_%2Cdgrid-css%2F%24_%2Cfont-mapapps%2Cgeometryservice%2Cmap-basemaps-api%2Cmap-config-api%2Cmap-init%2Cmap-preload-2D%2Cmap-widget%2Cmapdraw-api%2Cmapnavigation%2Cnotifier%2Cselection-services%2Csplashscreen%2Cstore-api%2Ctemplate-seasons%2Ctemplatelayout%2Ctemplatelayout-dijit%2Ctemplates%2Ctheme-everlasting%2F%24_%2Cthemes%2Ctoolrules%2Ctoolset%2Cwindowmanager}4.8.4%2C{esri%2F%24_}4.13.2%2C{maquette%2Fdist%2Fmaquette.umd.min}3.3.4%2C{whatwg-fetch%2Fdist%2Ffetch.umd}3.0.0%2C{dn_vuecolor%2Fdist%2Fvue-color.min}2.7.1%2C{vue%2Fvue.min}2.6.6%2C{moment%2Fmoment}2.24.0%2C{maquette-jsx%2Fdist%2Fmaquette-jsx.umd.min}2.1.1%2C{tslib%2Ftslib}1.9.3%2C{vuetify%2Fvuetify.min}1.5.18%2C{globalize%2Fdist%2Fglobalize}1.4.0%2C{dgrid%2FOnDemandGrid}1.2.1%2C{dijit%2Fmain%2Cdojo%2Fmain%2Cdojox%2Fmain}1.14.2%2C{dstore%2FStore}1.1.2%2C{maquette-css-transitions%2Fdist%2Fmaquette-css-transitions.umd.min}1.1.1%2C{dn_imprintprivacy}1.0.3%2C{apprt-polyfill%2Fpolyfill%2Cdn_sketchingenhanced%2Cdn_sketchingenhanced-command%2Cdn_sketchingenhanced-construction%2Cdn_sketchingenhanced-measurement%2Cdn_sketchingenhanced-snappingmanager%2Cdn_sketchingenhanced-styles%2Cdn_sketchingenhanced-symboleditor%2Cdn_sketchingenhanced-tools}1.0.0%2C{cldrjs%2Fdist%2Fcldr}0.5.0%2C{intersection-observer%2Fintersection-observer}0.4.2&requires_skip=apprt%404.8.4%2Flaunch%2Flayer%2Cdojo%401.14.2%2Fdojo&locale=en&app=downloads_sketching_enhanced&transitive=false&t=.js:175 TypeError: Cannot read property '' of null`

Could you also enable the measurement-functions in the demo-app?
Bonus: Does the measurement work in IE11? The current measurement2D-bundle does currently not AFAIK.

TIA.

**Comment by matthiasstein** [comment]
The layer menu button was removed with the new [release](https://github.com/conterra/mapapps-sketching-enhanced/releases/tag/1.0.1).
We have deactivated the measurement function in the demo, as it does not yet work properly with all sketching methods.
The measurement has the same limitations, since it is also based on the [client-side projection engine](https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-projection.html) used in the client-side [geometryEngine](https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-geometryEngine.html). These limitations concern projected reference systems.
